### ISSUE TITLE
Tsc error during first build

### ISSUE THREAD

**Issue by Lumene98** [scale-it/algorand-builder#216]
During the installation, the yarn build gives an error because the tsconfig of algob and runtime packages seem to be invalid 

![image](https://user-images.githubusercontent.com/26761348/106909021-239bb500-6700-11eb-99a1-585234667918.png)

**Comment by robert-zaremba** [comment]
@Lumene98 What's your typescript version? We require `4.0.x` or newer.

**Comment by lepidotteri** [comment]
@robert-zaremba we are not using any specific global TS version, rather -> https://github.com/blockchain-italia/algolend/blob/4f8f4ec8273c75f2d2b6f77e0daf40be4700e987/backend/package.json#L64

**Comment by robert-zaremba** [comment]
This website is not found (404): https://github.com/blockchain-italia/algolend/

It seams like you are using your own typescript setup. Could you create a project with that setup and share it? We can't replicate your issue. 

Also, could you copy an output of:
```
yarn run tsc --version
``

**Comment by Lumene98** [comment]
`` yarn run tsc --version -> Version 4.0.2 ``

I created this [repository](https://github.com/Lumene98/algorand_builder_test) where I cloned algorand builder and did only:
```
yarn install
yarn build
 ```

**Comment by robert-zaremba** [comment]
Thanks. Confirmed - we were able to replicate. We will handle it asap, sorry for problems.

**Comment by Lumene98** [comment]
> 
> 
> Thanks. Confirmed - we were able to replicate. We will handle it asap, sorry for problems.

Thank you for the immediate response

**Comment by robert-zaremba** [comment]
@Lumene98  we fixed it. Please check latest `master` and confirm that it works.

**Comment by Lumene98** [comment]
> 
> 
> @Lumene98 we fixed it. Please check latest `master` and confirm that it works.

```
$ yarn workspaces run build
> @algorand-builder/runtime
$ tsc --build . 
> @algorand-builder/algob
$ tsc --build . 
> @algorand-builder/types-algosdk
$ tsc
> example-asa
$ echo ok   
ok
> crowdfunding-application
$ echo ok
ok
> htlc-pyteal 
$ tsc --build .
> example-multisig
$ echo ok
ok
> nft-pyteal
$ echo ok
ok
> permissioned-voting-pyteal
$ echo ok
ok
> ref-templates
$ echo ok
ok  
> signed-txn-example
$ echo ok
ok 
Done in 28.90s.
```
Thanks all fixed for me!!
