### ISSUE TITLE
TS example doesn't work properly

### ISSUE THREAD

**Issue by Lumene98** [scale-it/algorand-builder#229]
In the typescript example, after doing `yarn build`:
```
yarn run algob deploy
yarn run algob run scripts/withdraw/htlc-withdraw.js
```
return errors because there is no script in scripts(only ts files) 

The solution should be to change the algob scripts folder to build/scripts

**Comment by amityadav0** [comment]
@Lumene98 Thanks for the info.
could you please try running `yarn run algob run scripts/withdraw/htlc-withdraw.ts` ?

**Comment by Lumene98** [comment]
> 
> 
> @Lumene98 Thanks for the info.
> could you please try running `yarn run algob run scripts/withdraw/htlc-withdraw.ts` ?

`failed during load: Cannot use import statement outside a module`

**Comment by amityadav0** [comment]
@Lumene98 one solution is to change the project tsconfig's outDir: "./build/scripts" -> "outDir": "./scripts". and then run yarn build again
Thanks, will add a fix for it.

**Comment by Lumene98** [comment]
> 
> 
> @Lumene98 one solution is to change the project tsconfig's outDir: "./build/scripts" -> "outDir": "./scripts". and then run yarn build again
> Thanks, will add a fix for it.

Thanks that should do it

**Comment by Lumene98** [comment]
When I tried it on my script it wouldn't let me deploy the stateful smart contract because I'm outside the alogob deploy

**Comment by amityadav0** [comment]
@Lumene98  To deploy asa or stateful smart contract you have to use `algob deploy`. `algob run` is used to interact with deployed asa or contracts.

**Comment by Lumene98** [comment]
> 
> 
> @Lumene98 To deploy asa or stateful smart contract you have to use `algob deploy`. `algob run` is used to interact with deployed asa or contracts.

Oh right I thought `algob deploy script.js` wasn't a thing, thank you!

**Comment by amityadav0** [comment]
thanks, adding it in docs as well.
