### ISSUE TITLE
AppLocalGetEx and AppGlobalGetEx return values

### ISSUE THREAD

**Issue by ori-shem-tov** [scale-it/algorand-builder#235]
In [packages/runtime/src/interpreter/opcode-list.ts](https://github.com/scale-it/algorand-builder/blob/master/packages/runtime/src/interpreter/opcode-list.ts), 
`AppLocalGetEx` and `AppGlobalGetEx` ops execution results in pushing `BIGINT0` to the stack in case the key doesn't have a corresponding value in app's state.

The actual behaviour should be pushing `BIGINT0` twice: one for the did_exist flag and one for the value.
This could result in an unwanted behaviour since the stack length is not as expected.

I've tested the above scenario with a simple TEAL script before posting this issue just to make sure but please validate as well.

**Comment by ratik21** [comment]
@ori-shem-tov thanks for taking the time and pointing this out. You seem right, validated `AppLocalGetEx` & `AppGlobalGetEx` behaviour using `teal-debugger`
![image](https://user-images.githubusercontent.com/33264364/108002079-67ea5780-7014-11eb-8343-c80e445d60d4.png)
Will update these opcodes ASAP.
