### ISSUE TITLE
scTmplParams from deploy.loadLogic shouldn't accept only string

### ISSUE THREAD

**Issue by Lumene98** [scale-it/algorand-builder#243]
While working on a ts application I realized that the accepted params for the smart contracts when loading python logic where only string but I think they could also be integer or something else since they are just params for python

**Comment by amityadav0** [comment]
we can pass numbers as well. Please refer to this example https://github.com/scale-it/algorand-builder/blob/606efcfe998f497bccd5b9e92f214664096ad50d/examples/restricted-assets/scripts/1-assetConfig.js#L14
Please let me know if this makes sense.

**Comment by Lumene98** [comment]
> we can pass numbers as well. Please refer to this example
> 
> https://github.com/scale-it/algorand-builder/blob/606efcfe998f497bccd5b9e92f214664096ad50d/examples/restricted-assets/scripts/1-assetConfig.js#L14
> 
> 
> Please let me know if this makes sense.

In JavaScript works, it's the typescript definition that only accept strings

**Comment by robert-zaremba** [comment]
We will add support for BigInts

**Comment by Lumene98** [comment]
> 
> 
> We will add support for BigInts

It's not a problem with BigInts, if you check scTmplParams in the type definition of loadLogic you'll see that it is map of strings but it should also accept other types

**Comment by amityadav0** [comment]
thanks, we will change that to support BigInts, string, number.

**Comment by robert-zaremba** [comment]
We should be careful with numbers - for big numbers we can have rounding errors, that's why `BigNum` are better.

**Comment by Lumene98** [comment]
> 
> 
> thanks, we will change that to support BigInts, string, number.

Thanks!

**Comment by Lumene98** [comment]
> 
> 
> We should be careful with numbers - for big numbers we can have rounding errors, that's why `BigNum` are better.

But it's simply to pass for example asset-ids or app-ids to non stateful smartcontracts as integer
